### ISSUE TITLE
Which branch to use?

### ISSUE THREAD

**Issue by mick-t** [stanford-rc/slurm-spank-spunnel#1]
Hi, 

I'm looking to use slurm-spank-stunnel, which branch should I use master or the tagged 0.2.1 branch? 

Thanks
Mick

**Comment by kcgthb** [comment]
Hi @mick-t 

`slurm-spank-stunnel` is unfortunately not maintained anymore, as we didn't find real use cases in our environment. 

That being said, `master` should be safe to use.

**Comment by mick-t** [comment]
Thanks!
