### ISSUE TITLE
slurm-23.11.4 compile fail 

### ISSUE THREAD

**Issue by lihang59860200** [stanford-rc/slurm-spank-spunnel#3]
In file included from slurm-spank-stunnel.c:47:
/data/slurm-23.11.4/slurm/spank.h:446:41: error: ‘SLURM_VERSION_NUMBER’ undeclared here (not in a function); did you mean ‘SLURM_VERSION_NUM’?
     const unsigned int plugin_version = SLURM_VERSION_NUMBER; \
                                         ^~~~~~~~~~~~~~~~~~~~
slurm-spank-stunnel.c:98:1: note: in expansion of macro ‘SPANK_PLUGIN’
 SPANK_PLUGIN(stunnel, 1);
 ^~~~~~~~~~~~
slurm-spank-stunnel.c: In function ‘_stunnel_connect_nodes’:
slurm-spank-stunnel.c:296:13: error: storage size of ‘hlist’ isn’t known
  hostlist_t hlist;
             ^~~~~

**Comment by kcgthb** [comment]
`SLURM_VERSION_NUMBER` is defined in `slurm/slurm_version.h`, you're probably missing that include, given the non-standard path `/data/slurm-23.11.4`.

The `hostlist_t` signature change in 23.11 has been addressed in 84d04e4ccfe538a09c3f17a52dde616903b66db8
